version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: app_development
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
